import dotenv from 'dotenv';
dotenv.config({ path: '../.env' });
import express, { type Request, type Response } from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import swaggerUi from 'swagger-ui-express';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { specs } from './config/swagger.js';
import { RegisterRoutes } from './generated/routes';
import { UserService } from './features/auth/services/UserService.js';
import { UserRepository } from './features/auth/repository/UserRepository.js';
import { UserFactionDeckService } from './features/auth/services/UserFactionDeckService.js';
import { GameService } from './features/game/services/GameService.js';
import { JwtService } from './features/auth/services/JwtService.js';
import { initializeMatchmaking } from './features/matchmaking/utils/MatchmakingHelper.js';
import { GameplayGateway } from './features/game/gateways/GameplayGateway.js';
import { getEnvVariableWithFallback } from 'gwen-common';

// Default env variables configuration

const DEFAULT_CORS_ORIGIN = 'http://localhost:5173';
const DEFAULT_PORT = '3000';
const DEFAULT_MONGODB_URI =
  'mongodb://gwen_user:gwen_password@localhost:27017/gwen?authSource=admin';
const DEFAULT_JWT_SECRET = 'GWEN_SERVER_2026_GRUAU_PASSERON_POTHIN_SECRET';
const DEFAULT_JWT_EXPIRATION = '3600000';
const DEFAULT_NODE_ENV = 'development';

// Actual env variables
export const CORS_ORIGIN = getEnvVariableWithFallback('CORS_ORIGIN', DEFAULT_CORS_ORIGIN);
export const PORT = getEnvVariableWithFallback('PORT', DEFAULT_PORT);
export const MONGODB_URI = getEnvVariableWithFallback('MONGODB_URI', DEFAULT_MONGODB_URI);
export const JWT_SECRET = getEnvVariableWithFallback('JWT_SECRET', DEFAULT_JWT_SECRET);
export const JWT_EXPIRATION = parseInt(
  getEnvVariableWithFallback('JWT_EXPIRATION', DEFAULT_JWT_EXPIRATION),
  10,
);
export const NODE_ENV = getEnvVariableWithFallback('NODE_ENV', DEFAULT_NODE_ENV);

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: CORS_ORIGIN,
    credentials: true,
  },
});

const jwtService = new JwtService(JWT_SECRET, JWT_EXPIRATION);

// CORS Configuration
const corsOptions = {
  origin: CORS_ORIGIN,
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
};

// Middleware
app.use(cors(corsOptions));
app.use(express.json());

// Swagger/OpenAPI documentation
app.use('/api-docs', swaggerUi.serve);
app.get('/api-docs', swaggerUi.setup(specs));
app.get('/api/openapi.json', (req: Request, res: Response) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(specs);
});

// Mount all the routes generated by tsoa
RegisterRoutes(app);

// WebSockets setup
app.locals.io = io;

// Authentication function used by tsoa for @Security('jwt')
export async function expressAuthentication(
  request: Request,
  securityName: string,
  scopes?: string[],
): Promise<any> {
  if (securityName !== 'jwt') {
    throw new Error('Unsupported security scheme');
  }

  const authHeader = request.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    const error = new Error('Missing or invalid Authorization header') as Error & {
      status?: number;
    };
    error.status = 401;
    throw error;
  }

  const token = authHeader.substring('Bearer '.length);

  try {
    const userId = jwtService.extractUserId(token);

    // On peut retourner un objet user minimal pour l’instant
    return { userId };
  } catch {
    const error = new Error('Invalid or expired token') as Error & { status?: number };
    error.status = 401;
    throw error;
  }
}

// Initialize MongoDB and start server
async function startServer() {
  try {
    console.log('Connecting to database @ ', MONGODB_URI);
    await mongoose.connect(MONGODB_URI);
    console.log('MongoDB connected successfully');

    // Initialize services
    const userRepository = new UserRepository();
    const userService = new UserService(userRepository);
    const userFactionDeckService = new UserFactionDeckService();
    const gameService = new GameService();

    // Initialize matchmaking system
    initializeMatchmaking(io, userService, gameService, userFactionDeckService);

    // Initialize gameplay system
    new GameplayGateway(io);

    httpServer.listen(PORT, () => {
      console.log(`Server started on port ${PORT}`);
      console.log(`CORS origin: ${CORS_ORIGIN}`);
    });
  } catch (error) {
    console.error('MongoDB connection error:', error);
    process.exit(1);
  }
}

void startServer();
