import express, { type Request, type Response } from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import swaggerUi from 'swagger-ui-express';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { specs } from './config/swagger.js';
import { RegisterRoutes } from './generated/routes';
import { UserService } from './features/auth/services/UserService.js';
import { UserRepository } from './features/auth/repository/UserRepository.js';
import { GameService } from './features/game/services/GameService.js';
import { JwtService } from './features/auth/services/JwtService.js';
import { initializeMatchmaking } from './features/matchmaking/utils/MatchmakingHelper';

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: 'http://localhost:5173',
    credentials: true,
  },
});
const PORT = process.env.PORT || 3000;
const MONGODB_URI =
  process.env.MONGODB_URI ||
  'mongodb://gwen-user:gwen-password@localhost:27017/gwen-db?authSource=admin';

const jwtSecret = process.env.JWT_SECRET || 'your-secret-key';
const jwtExpiration = parseInt(process.env.JWT_EXPIRATION || '3600000', 10);
const jwtService = new JwtService(jwtSecret, jwtExpiration);

// CORS Configuration
const corsOptions = {
  origin: process.env.CORS_ORIGIN || 'http://localhost:5173',
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
};

// Middleware
app.use(cors(corsOptions));
app.use(express.json());

// Swagger/OpenAPI documentation
app.use('/api-docs', swaggerUi.serve);
app.get('/api-docs', swaggerUi.setup(specs));
app.get('/api/openapi.json', (req: Request, res: Response) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(specs);
});

// Mount all the routes generated by tsoa
RegisterRoutes(app);

// WebSockets setup
app.locals.io = io;

// Authentication function used by tsoa for @Security('jwt')
export async function expressAuthentication(
  request: Request,
  securityName: string,
  scopes?: string[],
): Promise<any> {
  if (securityName !== 'jwt') {
    throw new Error('Unsupported security scheme');
  }

  const authHeader = request.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    const error = new Error('Missing or invalid Authorization header') as Error & {
      status?: number;
    };
    error.status = 401;
    throw error;
  }

  const token = authHeader.substring('Bearer '.length);

  try {
    const userId = jwtService.extractUserId(token);

    // On peut retourner un objet user minimal pour l’instant
    return { userId };
  } catch {
    const error = new Error('Invalid or expired token') as Error & { status?: number };
    error.status = 401;
    throw error;
  }
}

// Initialize MongoDB and start server
async function startServer() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('MongoDB connected successfully');

    // Initialize services
    const userRepository = new UserRepository();
    const userService = new UserService(userRepository);
    const gameService = new GameService();

    // Initialize matchmaking system
    initializeMatchmaking(io, userService, gameService);

    httpServer.listen(PORT, () => {
      console.log(`Server started on http://localhost:${PORT}`);
    });
  } catch (error) {
    console.error('MongoDB connection error:', error);
    process.exit(1);
  }
}

void startServer();
