import express, { type Request, type Response } from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import swaggerUi from 'swagger-ui-express';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { specs } from './config/swagger.js';
import { RegisterRoutes } from './generated/routes';
import { UserService } from './features/auth/services/UserService.js';
import { UserRepository } from './features/auth/repository/UserRepository.js';
import { UserFactionDeckService } from './features/auth/services/UserFactionDeckService.js';
import { GameService } from './features/game/services/GameService.js';
import { JwtService } from './features/auth/services/JwtService.js';
import { initializeMatchmaking } from './features/matchmaking/utils/MatchmakingHelper.js';
import { GameplayGateway } from './features/game/gateways/GameplayGateway.js';
import { getEnvVariableWithFallback } from 'gwen-common';

// Default env variables configuration

const DEFAULT_CORS_ORIGIN = 'http://localhost:5173';
const DEFAULT_PORT = '3000';
const DEFAULT_MONGODB_URI =
  'mongodb://gwen_user:gwen_password@localhost:27017/gwen?authSource=admin';
const DEFAULT_JWT_SECRET = 'GWEN_SERVER_2026_GRUAU_PASSERON_POTHIN_SECRET';
const DEFAULT_JWT_EXPIRATION = '3600000';
const DEFAULT_NODE_ENV = 'development';

// Actual env variables
export const CORS_ORIGIN = getEnvVariableWithFallback('CORS_ORIGIN', DEFAULT_CORS_ORIGIN);
export const PORT = getEnvVariableWithFallback('PORT', DEFAULT_PORT);
export const MONGODB_URI = getEnvVariableWithFallback('MONGODB_URI', DEFAULT_MONGODB_URI);
export const JWT_SECRET = getEnvVariableWithFallback('JWT_SECRET', DEFAULT_JWT_SECRET);
export const JWT_EXPIRATION = parseInt(
  getEnvVariableWithFallback('JWT_EXPIRATION', DEFAULT_JWT_EXPIRATION),
  10,
);
export const NODE_ENV = getEnvVariableWithFallback('NODE_ENV', DEFAULT_NODE_ENV);
export const GWEN_LOGS = getEnvVariableWithFallback('GWEN_LOGS', 'true') === 'true';

// Load local .env file only in non-production environments.
// On platforms like Render, environment variables should be configured in the dashboard.
if (NODE_ENV !== 'production') {
  const { default: dotenv } = await import('dotenv');
  dotenv.config({ path: '../.env' });
}

if (GWEN_LOGS) {
  console.log('[BOOT][ENV]', {
    nodeEnv: NODE_ENV,
    jwtSecretPresent: !!process.env.JWT_SECRET,
    jwtSecretLength: process.env.JWT_SECRET?.length ?? 0,
  });
}

// Fail fast in production if JWT_SECRET is missing/empty.
if (NODE_ENV === 'production' && !process.env.JWT_SECRET) {
  console.error('[BOOT][FATAL] JWT_SECRET is missing in production environment.');
  process.exit(1);
}

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: CORS_ORIGIN,
    credentials: true,
  },
});

const jwtService = new JwtService(JWT_SECRET, JWT_EXPIRATION);

// CORS Configuration
const corsOptions = {
  origin: CORS_ORIGIN,
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
};

// Global request logger (if enabled)
if (GWEN_LOGS) {
  app.use((req, res, next) => {
    console.log(`[REQUEST] ${req.method} ${req.originalUrl}`, {
      headers: req.headers,
      body: req.body,
    });
    next();
  });
}

app.use(cors(corsOptions));
app.use(express.json());

// Swagger/OpenAPI documentation
app.use('/api-docs', swaggerUi.serve);
app.get('/api-docs', swaggerUi.setup(specs));
app.get('/api/openapi.json', (req: Request, res: Response) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(specs);
});

// Mount all the routes generated by tsoa
RegisterRoutes(app);

// WebSockets setup
app.locals.io = io;

// Authentication function used by tsoa for @Security('jwt')
export async function expressAuthentication(
  request: Request,
  securityName: string,
  scopes?: string[],
): Promise<any> {
  if (securityName !== 'jwt') {
    if (GWEN_LOGS) {
      console.warn('[AUTH] Unsupported security scheme', { securityName });
    }
    throw new Error('Unsupported security scheme');
  }

  const authHeader = request.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    if (GWEN_LOGS) {
      console.warn('[AUTH] Missing or invalid Authorization header', {
        url: request.originalUrl,
        headers: request.headers,
      });
    }
    const error = new Error('Missing or invalid Authorization header') as Error & {
      status?: number;
    };
    error.status = 401;
    throw error;
  }

  const token = authHeader.substring('Bearer '.length);

  try {
    const userId = jwtService.extractUserId(token);
    if (GWEN_LOGS) {
      console.log('[AUTH] JWT validated', { userId, url: request.originalUrl });
    }
    return { userId };
  } catch (err) {
    if (GWEN_LOGS) {
      console.error('[AUTH] Invalid or expired token', {
        error: err,
        url: request.originalUrl,
      });
    }
    const error = new Error('Invalid or expired token') as Error & { status?: number };
    error.status = 401;
    throw error;
  }
}

// Global error logger (if enabled)
if (GWEN_LOGS) {
  app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
    console.error('[ERROR]', {
      url: req.originalUrl,
      method: req.method,
      message: err.message,
      stack: err.stack,
    });
    next(err);
  });
}

// Initialize MongoDB and start server
async function startServer() {
  try {
    if (GWEN_LOGS) {
      console.log('Connecting to database @ ', MONGODB_URI);
    }
    await mongoose.connect(MONGODB_URI);
    if (GWEN_LOGS) {
      console.log('MongoDB connected successfully');
    }

    // Initialize services
    const userRepository = new UserRepository();
    const userService = new UserService(userRepository);
    const userFactionDeckService = new UserFactionDeckService();
    const gameService = new GameService();

    // Initialize matchmaking system
    initializeMatchmaking(io, userService, gameService, userFactionDeckService);

    // Initialize gameplay system
    new GameplayGateway(io);

    httpServer.listen(PORT, () => {
      if (GWEN_LOGS) {
        console.log(`Server started on port ${PORT}`);
        console.log(`CORS origin: ${CORS_ORIGIN}`);
      }
    });
  } catch (error) {
    if (GWEN_LOGS) {
      console.error('MongoDB connection error:', error);
    }
    process.exit(1);
  }
}

void startServer();
