import type { FactionConfig } from '../../types/game/FactionConfig';

export const NORTHERN_REALMS: FactionConfig = {
  name: 'Northern Realms',
  iconUrl: '',
  characters: [
    {
      name: 'Geralt of Rivia',
      power: 15,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/geralt_of_rivia.png',
    },
    {
      name: 'Cirilla Fiona Elen Riannon',
      power: 15,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/ciri.png',
    },
    {
      name: 'Vernon Roche',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/vernon_roche.png',
    },
    {
      name: 'John Natalis',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/john_natalis.png',
    },
    {
      name: 'Philippa Eilhart',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/philippa_eilhart.png',
    },
    {
      name: 'Esterad Thyssen',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/esterad_thyssen.png',
    },
    {
      name: 'Yarpen Zigrin',
      power: 2,
      description: 'No special ability.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/yarpen_zigrin.png',
    },
    {
      name: 'Prince Stennis',
      power: 5,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'SPY',
      imageUrl: '/cards/northern-realms/prince_stennis.png',
    },
    {
      name: 'Sigismund Dijkstra',
      power: 4,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'SPY',
      imageUrl: '/cards/northern-realms/dijkstra.png',
    },
    {
      name: 'Thaler',
      power: 1,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'SIEGE',
      ability: 'SPY',
      imageUrl: '/cards/northern-realms/thaler.png',
    },
    {
      name: 'Dun Banner Medic',
      power: 5,
      description: 'Medic. Revive a non-hero unit from discard.',
      isHero: false,
      ranges: 'SIEGE',
      ability: 'MEDIC',
      imageUrl: '/cards/northern-realms/dun_banner_medic.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Catapult',
      power: 8,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'SIEGE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/catapult.png',
    },
    {
      name: 'Catapult',
      power: 8,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      ranges: 'SIEGE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/northern-realms/catapult.png',
    },
    {
      name: 'Ballista',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/ballista.png',
    },
    {
      name: 'Trebuchet',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/trebuchet.png',
    },
    {
      name: 'Trebuchet',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/trebuchet.png',
    },
  ],
  leaders: [
    {
      name: 'Foltest – The Siegemaster',
      description:
        "Doubles the strength of all your Siege units (unless a Commander's Horn is also present on that row).",
      imageUrl: '/leaders/northern-realms/foltest_siegemaster.png',
      ability: 'HORN_SIEGE',
    },
    {
      name: 'Foltest – King of Temeria',
      description: 'Pick an Impenetrable Fog card from your deck and play it instantly.',
      imageUrl: '/leaders/northern-realms/foltest_king_of_temeria.png',
      ability: 'PLAY_FOG_FROM_DECK',
    },
    {
      name: 'Foltest – The Steel-Forged',
      description:
        "Destroy your enemy's strongest Siege unit(s) if the combined strength of all his or her Siege units is 10 or more.",
      imageUrl: '/leaders/northern-realms/foltest_steel_forged.png',
      ability: 'SCORCH_SIEGE',
    },
    {
      name: 'Foltest – Son of Medell',
      description:
        "Destroy your enemy's strongest Ranged Combat unit(s) if the combined strength of all his or her Ranged Combat units is 10 or more.",
      imageUrl: '/leaders/northern-realms/foltest_son_of_medell.png',
      ability: 'SCORCH_RANGED',
    },
    {
      name: 'Foltest – Lord Commander of the North',
      description: 'Clear any weather effects currently in play.',
      imageUrl: '/leaders/northern-realms/foltest_lord_commander.png',
      ability: 'CLEAR_WEATHER',
    },
  ],
};
