import type { Faction } from '../../types/game/Faction';

export const NORTHERN_REALMS: Faction = {
  name: 'Northern Realms',
  iconUrl: '',
  characters: [
    {
      name: 'Geralt of Rivia',
      power: 15,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/geralt_of_rivia.png',
    },
    {
      name: 'Cirilla Fiona Elen Riannon',
      power: 15,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/ciri.png',
    },
    {
      name: 'Vernon Roche',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/vernon_roche.png',
    },
    {
      name: 'John Natalis',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/john_natalis.png',
    },
    {
      name: 'Philippa Eilhart',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/philippa_eilhart.png',
    },
    {
      name: 'Esterad Thyssen',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/esterad_thyssen.png',
    },
    {
      name: 'Yarpen Zigrin',
      power: 2,
      description: 'No special ability.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/yarpen_zigrin.png',
    },
    {
      name: 'Prince Stennis',
      power: 5,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/prince_stennis.png',
    },
    {
      name: 'Sigismund Dijkstra',
      power: 4,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/dijkstra.png',
    },
    {
      name: 'Thaler',
      power: 1,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/thaler.png',
    },
    {
      name: 'Dun Banner Medic',
      power: 5,
      description: 'Medic. Revive a non-hero unit from discard.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/dun_banner_medic.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Blue Stripes Commando',
      power: 4,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/northern-realms/blue_stripes_commando.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Crinfrid Reavers Dragon Hunter',
      power: 5,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/northern-realms/crinfrid_reavers.png',
    },
    {
      name: 'Catapult',
      power: 8,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/catapult.png',
    },
    {
      name: 'Catapult',
      power: 8,
      description: 'Tight Bond. Doubles strength when next to same card.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/catapult.png',
    },
    {
      name: 'Ballista',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'siege',
      imageUrl: '/cards/northern-realms/ballista.png',
    },
    {
      name: 'Trebuchet',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/trebuchet.png',
    },
    {
      name: 'Trebuchet',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/northern-realms/trebuchet.png',
    },
  ],
};
