import type { FactionConfig } from '../../../types/game/FactionConfig';

export const MONSTERS: FactionConfig = {
  id: 'monsters',
  name: 'Monsters',
  iconUrl: '',
  cardBackIconUrl: '/back/monsters_back.png',
  units: [
    {
      id: 'arachas_1',
      name: 'Arachas',
      strength: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/arachas_1.png',
    },
    {
      id: 'arachas_2',
      name: 'Arachas',
      strength: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/arachas_2.png',
    },
    {
      id: 'arachas_3',
      name: 'Arachas',
      strength: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/arachas_3.png',
    },

    {
      id: 'arachas_behemoth',
      name: 'Arachas Behemoth',
      strength: 6,
      description: 'Summons all Arachas Behemoth cards from your deck.',
      isHero: false,
      range: 'SIEGE',
      ability: 'MUSTER',
      imageUrl: '/monsters/arachas_behemoth.png',
    },

    {
      id: 'botchling',
      name: 'Botchling',
      strength: 4,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/monsters/botchling.png',
    },

    {
      id: 'celaeno_harpy',
      name: 'Celaeno Harpy',
      strength: 2,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/monsters/celaeno_harpy.png',
    },

    {
      id: 'cockatrice',
      name: 'Cockatrice',
      strength: 2,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/monsters/cockatrice.png',
    },

    {
      id: 'crone_brewess',
      name: 'Crone: Brewess',
      strength: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/crone_brewess.png',
    },
    {
      id: 'crone_weavess',
      name: 'Crone: Weavess',
      strength: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/crone_weavess.png',
    },
    {
      id: 'crone_whispess',
      name: 'Crone: Whispess',
      strength: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/crone_whispess.png',
    },

    {
      id: 'draug',
      name: 'Draug',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'MELEE',
      imageUrl: '/monsters/draug.png',
    },

    {
      id: 'earth_elemental',
      name: 'Earth Elemental',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/monsters/earth_elemental.png',
    },

    {
      id: 'harpy',
      name: 'Harpy',
      strength: 2,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/monsters/harpy.png',
    },

    {
      id: 'ice_giant',
      name: 'Ice Giant',
      strength: 5,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/monsters/ice_giant.png',
    },

    {
      id: 'imlerith',
      name: 'Imlerith',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'MELEE',
      imageUrl: '/monsters/imlerith.png',
    },

    {
      id: 'kayran',
      name: 'Kayran',
      strength: 8,
      description: 'Hero. Adds +1 power to all cards in the same row.',
      isHero: true,
      range: 'AGILE',
      ability: 'MORAL_BOOST',
      imageUrl: '/monsters/kayran.png',
    },

    {
      id: 'leshen',
      name: 'Leshen',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/monsters/leshen.png',
    },

    {
      id: 'nekker_1',
      name: 'Nekker',
      strength: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/nekker_1.png',
    },
    {
      id: 'nekker_2',
      name: 'Nekker',
      strength: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/nekker_2.png',
    },
    {
      id: 'nekker_3',
      name: 'Nekker',
      strength: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/monsters/nekker_3.png',
    },

    {
      id: 'plague_maiden',
      name: 'Plague Maiden',
      strength: 5,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/monsters/plague_maiden.png',
    },

    {
      id: 'toad',
      name: 'Toad',
      strength: 7,
      description: 'Destroy strongest enemy ranged units if total ranged >= 10.',
      isHero: false,
      range: 'RANGED',
      ability: 'SCORCH',
      imageUrl: '/monsters/toad.png',
    },
  ],
  leaders: [
    {
      id: 'eredin_king_of_the_wild_hunt',
      name: 'Eredin: King of the Wild Hunt',
      description: 'Pick any weather card from your deck and play it instantly.',
      imageUrl: '/monsters/eredin_king_of_the_wild_hunt.png',
      ability: 'PLAY_WEATHER_FROM_DECK',
    },
    {
      id: 'eredin_commander_of_the_red_riders',
      name: 'Eredin: Commander of the Red Riders',
      description: 'Double the strength of all your Close Combat units.',
      imageUrl: '/monsters/eredin_commander_of_the_red_riders.png',
      ability: 'HORN_MELEE',
    },
    {
      id: 'eredin_bringer_of_death',
      name: 'Eredin: Bringer of Death',
      description: 'Discard 2 cards and draw 1 card of your choice from your deck.',
      imageUrl: '/monsters/eredin_bringer_of_death.png',
      ability: 'DISCARD_AND_DRAW',
    },
    {
      id: 'eredin_destroyer_of_worlds',
      name: 'Eredin: Destroyer of Worlds',
      description: 'Restore a card from your discard pile to your hand.',
      imageUrl: '/monsters/eredin_destroyer_of_worlds.png',
      ability: 'REVIVE_FROM_GRAVEYARD',
    },
    {
      id: 'eredin_breacc_glas_the_treacherous',
      name: 'Eredin Bréacc Glas: The Treacherous',
      description: 'Doubles the strength of all spy cards (affects both players).',
      imageUrl: '/monsters/eredin_breacc_glas_the_treacherous.png',
      ability: 'DOUBLE_SPY_STRENGTH',
    },
  ],
};
