import type { FactionConfig } from '../../../types/game/FactionConfig';

export const MONSTERS: FactionConfig = {
  name: 'Monsters',
  iconUrl: '',
  characters: [
    {
      name: 'Arachas',
      power: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/arachas.png',
    },
    {
      name: 'Arachas',
      power: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/arachas.png',
    },
    {
      name: 'Arachas',
      power: 4,
      description: 'Summons all Arachas cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/arachas.png',
    },

    {
      name: 'Arachas Behemoth',
      power: 6,
      description: 'Summons all Arachas Behemoth cards from your deck.',
      isHero: false,
      ranges: 'SIEGE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/arachas_behemoth.png',
    },

    {
      name: 'Botchling',
      power: 4,
      description: 'No special ability.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/monsters/botchling.png',
    },

    {
      name: 'Celaeno Harpy',
      power: 2,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      ranges: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/monsters/celaeno_harpy.png',
    },

    {
      name: 'Cockatrice',
      power: 2,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/monsters/cockatrice.png',
    },

    {
      name: 'Crone: Brewess',
      power: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/crone_brewess.png',
    },
    {
      name: 'Crone: Weavess',
      power: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/crone_weavess.png',
    },
    {
      name: 'Crone: Whispess',
      power: 6,
      description: 'Summons all Crones from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/crone_whispess.png',
    },

    {
      name: 'Draug',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/monsters/draug.png',
    },

    {
      name: 'Earth Elemental',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/monsters/earth_elemental.png',
    },

    {
      name: 'Harpy',
      power: 2,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      ranges: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/monsters/harpy.png',
    },

    {
      name: 'Ice Giant',
      power: 5,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/monsters/ice_giant.png',
    },

    {
      name: 'Imlerith',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/monsters/imlerith.png',
    },

    {
      name: 'Kayran',
      power: 8,
      description: 'Hero. Adds +1 power to all cards in the same row.',
      isHero: true,
      ranges: ['MELEE', 'RANGED'],
      ability: 'MORAL_BOOST',
      imageUrl: '/cards/monsters/kayran.png',
    },

    {
      name: 'Leshen',
      power: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/monsters/leshen.png',
    },

    {
      name: 'Nekker',
      power: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/nekker.png',
    },
    {
      name: 'Nekker',
      power: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/nekker.png',
    },
    {
      name: 'Nekker',
      power: 2,
      description: 'Summons all Nekker cards from your deck.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/monsters/nekker.png',
    },

    {
      name: 'Plague Maiden',
      power: 5,
      description: 'No special ability.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/monsters/plague_maiden.png',
    },

    {
      name: 'Toad',
      power: 7,
      description: 'Destroy strongest enemy ranged units if total ranged >= 10.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'SCORCH',
      imageUrl: '/cards/monsters/toad.png',
    },
  ],
  leaders: [
    {
      name: 'Eredin: King of the Wild Hunt',
      description: 'Pick any weather card from your deck and play it instantly.',
      imageUrl: '/leaders/monsters/eredin_king_of_the_wild_hunt.png',
      ability: 'PLAY_WEATHER_FROM_DECK',
    },
    {
      name: 'Eredin: Commander of the Red Riders',
      description: 'Double the strength of all your Close Combat units.',
      imageUrl: '/leaders/monsters/eredin_commander_of_the_red_riders.png',
      ability: 'HORN_MELEE',
    },
    {
      name: 'Eredin: Bringer of Death',
      description: 'Discard 2 cards and draw 1 card of your choice from your deck.',
      imageUrl: '/leaders/monsters/eredin_bringer_of_death.png',
      ability: 'DISCARD_AND_DRAW',
    },
    {
      name: 'Eredin: Destroyer of Worlds',
      description: 'Restore a card from your discard pile to your hand.',
      imageUrl: '/leaders/monsters/eredin_destroyer_of_worlds.png',
      ability: 'REVIVE_FROM_GRAVEYARD',
    },
    {
      name: 'Eredin Bréacc Glas: The Treacherous',
      description: 'Doubles the strength of all spy cards (affects both players).',
      imageUrl: '/leaders/monsters/eredin_treacherous.png',
      ability: 'DOUBLE_SPY_STRENGTH',
    },
  ],
};
