import type { FactionConfig } from '../../../types/game/FactionConfig';

export const NILFGAARD: FactionConfig = {
  name: 'Nilfgaard',
  iconUrl: '',
  leaders: [
    {
      name: 'Emhyr var Emreis – His Imperial Majesty',
      description: 'Pick a Torrential Rain card from your deck and play it instantly.',
      imageUrl: '/leaders/nilfgaard/emhyr_his_imperial_majesty.png',
      ability: 'PLAY_RAIN_FROM_DECK',
    },
    {
      name: 'Emhyr var Emreis – Emperor of Nilfgaard',
      description: "Look at 3 random cards from your opponent's hand.",
      imageUrl: '/leaders/nilfgaard/emhyr_emperor_of_nilfgaard.png',
      ability: 'SPY_OPPONENT_HAND',
    },
    {
      name: 'Emhyr var Emreis – Invader of the North',
      description: 'Abilities that restore a unit restore a randomly chosen unit.',
      imageUrl: '/leaders/nilfgaard/emhyr_invader_of_the_north.png',
      ability: 'RANDOM_REVIVE',
    },
    {
      name: 'Emhyr var Emreis – The Relentless',
      description: "Draw a card from your opponent's discard pile.",
      imageUrl: '/leaders/nilfgaard/emhyr_the_relentless.png',
      ability: 'STEAL_FROM_GRAVEYARD',
    },
    {
      name: 'Emhyr var Emreis – The White Flame',
      description: "Cancel your opponent's Leader Ability.",
      imageUrl: '/leaders/nilfgaard/emhyr_white_flame.png',
      ability: 'CANCEL_LEADER_ABILITY',
    },
  ],
  characters: [
    {
      name: 'Albrich',
      power: 2,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/albrich.png',
    },
    {
      name: 'Assire var Anahid',
      power: 6,
      description: 'Medic. Revive a non-hero unit from discard.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/cards/nilfgaard/assire_var_anahid.png',
    },
    {
      name: 'Black Infantry Archer',
      power: 10,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/black_infantry_archer.png',
    },
    {
      name: 'Black Infantry Archer',
      power: 10,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/black_infantry_archer.png',
    },
    {
      name: 'Cahir Mawr Dyffryn aep Ceallach',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'MELEE',
      imageUrl: '/cards/nilfgaard/cahir.png',
    },
    {
      name: 'Cynthia',
      power: 4,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/cynthia.png',
    },
    {
      name: 'Etolian Auxiliary Archers',
      power: 4,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/etolian_auxiliary_archers.png',
    },
    {
      name: 'Etolian Auxiliary Archers',
      power: 4,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/etolian_auxiliary_archers.png',
    },
    {
      name: 'Fringilla Vigo',
      power: 6,
      description: 'No special ability.',
      isHero: false,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/fringilla_vigo.png',
    },
    {
      name: 'Heavy Zerrikanian Fire Scorpion',
      power: 10,
      description: 'No special ability.',
      isHero: false,
      ranges: 'SIEGE',
      imageUrl: '/cards/nilfgaard/heavy_zerrikanian_fire_scorpion.png',
    },
    {
      name: 'Impera Brigade Guard',
      power: 3,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/impera_brigade_guard.png',
    },
    {
      name: 'Impera Brigade Guard',
      power: 3,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/impera_brigade_guard.png',
    },
    {
      name: 'Impera Brigade Guard',
      power: 3,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/impera_brigade_guard.png',
    },
    {
      name: 'Letho of Gulet',
      power: 10,
      description: 'Hero.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/nilfgaard/letho_of_gulet.png',
    },
    {
      name: 'Menno Coehoorn',
      power: 10,
      description: 'Hero Medic.',
      isHero: true,
      ranges: 'MELEE',
      ability: 'MEDIC',
      imageUrl: '/cards/nilfgaard/menno_coehoorn.png',
    },
    {
      name: 'Morvran Voorhis',
      power: 10,
      description: 'Hero.',
      isHero: true,
      ranges: 'MELEE',
      imageUrl: '/cards/nilfgaard/morvran_voorhis.png',
    },
    {
      name: 'Nausicaa Cavalry Rider',
      power: 2,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/nausicaa_cavalry_rider.png',
    },
    {
      name: 'Nausicaa Cavalry Rider',
      power: 2,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/nausicaa_cavalry_rider.png',
    },
    {
      name: 'Nausicaa Cavalry Rider',
      power: 2,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/nausicaa_cavalry_rider.png',
    },
    {
      name: 'Shilard Fitz-Oesterlen',
      power: 7,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'SPY',
      imageUrl: '/cards/nilfgaard/shilard.png',
    },
    {
      name: 'Stefan Skellen',
      power: 9,
      description: 'Spy.',
      isHero: false,
      ranges: 'MELEE',
      ability: 'SPY',
      imageUrl: '/cards/nilfgaard/stefan_skellen.png',
    },
    {
      name: 'Tibor Eggebracht',
      power: 10,
      description: 'Hero.',
      isHero: true,
      ranges: 'RANGED',
      imageUrl: '/cards/nilfgaard/tibor_eggebracht.png',
    },
    {
      name: 'Vattier de Rideaux',
      power: 4,
      description: 'Spy.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'SPY',
      imageUrl: '/cards/nilfgaard/vattier_de_rideaux.png',
    },
    {
      name: 'Young Emissary',
      power: 5,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/young_emissary.png',
    },
    {
      name: 'Young Emissary',
      power: 5,
      description: 'Tight Bond.',
      isHero: false,
      ranges: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/cards/nilfgaard/young_emissary.png',
    },
  ],
};
