import type { FactionConfig } from '../../../types/game/FactionConfig';

export const NORTHERN_REALMS: FactionConfig = {
  id: 'northern_realms',
  name: 'Northern Realms',
  iconUrl: '',
  cardBackIconUrl: '/back/northern_realms_back.jpg',
  units: [
    {
      id: 'vernon_roche',
      name: 'Vernon Roche',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'MELEE',
      imageUrl: '/northern-realms/vernon_roche.png',
    },
    {
      id: 'john_natalis',
      name: 'John Natalis',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'MELEE',
      imageUrl: '/northern-realms/john_natalis.png',
    },
    {
      id: 'philippa_eilhart',
      name: 'Philippa Eilhart',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/northern-realms/philippa_eilhart.png',
    },
    {
      id: 'esterad_thyssen',
      name: 'Esterad Thyssen',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/northern-realms/esterad_thyssen.png',
    },
    {
      id: 'yarpen_zigrin',
      name: 'Yarpen Zigrin',
      strength: 2,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/northern-realms/yarpen_zigrin.png',
    },
    {
      id: 'prince_stennis',
      name: 'Prince Stennis',
      strength: 5,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      range: 'MELEE',
      ability: 'SPY',
      imageUrl: '/northern-realms/prince_stennis.png',
    },
    {
      id: 'sigismund_dijkstra',
      name: 'Sigismund Dijkstra',
      strength: 4,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      range: 'RANGED',
      ability: 'SPY',
      imageUrl: '/northern-realms/sigismund_dijkstra.png',
    },
    {
      id: 'thaler',
      name: 'Thaler',
      strength: 1,
      description: 'Spy. Place on opponent field and draw 2 cards.',
      isHero: false,
      range: 'SIEGE',
      ability: 'SPY',
      imageUrl: '/northern-realms/thaler.png',
    },
    {
      id: 'dun_banner_medic',
      name: 'Dun Banner Medic',
      strength: 5,
      description: 'Medic. Revive a non-hero unit from discard.',
      isHero: false,
      range: 'SIEGE',
      ability: 'MEDIC',
      imageUrl: '/northern-realms/dun_banner_medic.png',
    },
    {
      id: 'blue_stripes_commando_1',
      name: 'Blue Stripes Commando',
      strength: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/blue_stripes_commando_1.png',
    },
    {
      id: 'blue_stripes_commando_2',
      name: 'Blue Stripes Commando',
      strength: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/blue_stripes_commando_2.png',
    },
    {
      id: 'blue_stripes_commando_3',
      name: 'Blue Stripes Commando',
      strength: 4,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'MELEE',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/blue_stripes_commando_3.png',
    },
    {
      id: 'crinfrid_reavers_dragon_hunter_1',
      name: 'Crinfrid Reavers Dragon Hunter',
      strength: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/crinfrid_reavers_1.png',
    },
    {
      id: 'crinfrid_reavers_dragon_hunter_2',
      name: 'Crinfrid Reavers Dragon Hunter',
      strength: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/crinfrid_reavers_2.png',
    },
    {
      id: 'crinfrid_reavers_dragon_hunter_3',
      name: 'Crinfrid Reavers Dragon Hunter',
      strength: 5,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'RANGED',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/crinfrid_reavers_3.png',
    },
    {
      id: 'catapult_1',
      name: 'Catapult',
      strength: 8,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'SIEGE',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/catapult_1.png',
    },
    {
      id: 'catapult_2',
      name: 'Catapult',
      strength: 8,
      description: 'Tight Bond. Multiplies strength with identical cards.',
      isHero: false,
      range: 'SIEGE',
      ability: 'TIGHT_BOND',
      imageUrl: '/northern-realms/catapult_2.png',
    },
    {
      id: 'ballista_1',
      name: 'Ballista',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/northern-realms/ballista_1.png',
    },
    {
      id: 'ballista_2',
      name: 'Ballista',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/northern-realms/ballista_2.png',
    },
    {
      id: 'trebuchet_1',
      name: 'Trebuchet',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/northern-realms/trebuchet_1.png',
    },
    {
      id: 'trebuchet_2',
      name: 'Trebuchet',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'SIEGE',
      imageUrl: '/northern-realms/trebuchet_2.png',
    },
  ],
  leaders: [
    {
      id: 'foltest_the_siegemaster',
      name: 'Foltest – The Siegemaster',
      description:
        "Doubles the strength of all your Siege units (unless a Commander's Horn is also present on that row).",
      imageUrl: '/northern-realms/foltest_the_siegemaster.png',
      ability: 'HORN_SIEGE',
    },
    {
      id: 'foltest_king_of_temeria',
      name: 'Foltest – King of Temeria',
      description: 'Pick an Impenetrable Fog card from your deck and play it instantly.',
      imageUrl: '/northern-realms/foltest_king_of_temeria.png',
      ability: 'PLAY_FOG_FROM_DECK',
    },
    {
      id: 'foltest_the_steel_forged',
      name: 'Foltest – The Steel-Forged',
      description:
        "Destroy your enemy's strongest Siege unit(s) if the combined strength of all his or her Siege units is 10 or more.",
      imageUrl: '/northern-realms/foltest_the_steel_forged.png',
      ability: 'SCORCH_SIEGE',
    },
    {
      id: 'foltest_son_of_medell',
      name: 'Foltest – Son of Medell',
      description:
        "Destroy your enemy's strongest Ranged Combat unit(s) if the combined strength of all his or her Ranged Combat units is 10 or more.",
      imageUrl: '/northern-realms/foltest_son_of_medell.png',
      ability: 'SCORCH_RANGED',
    },
    {
      id: 'foltest_lord_commander_of_the_north',
      name: 'Foltest – Lord Commander of the North',
      description: 'Clear any weather effects currently in play.',
      imageUrl: '/northern-realms/foltest_lord_commander_of_the_north.png',
      ability: 'CLEAR_WEATHER',
    },
  ],
};
