import type { FactionConfig } from '../../../types/game/FactionConfig';

export const SCOIATAEL: FactionConfig = {
  name: 'Monsters',
  iconUrl: '',
  characters: [
    {
      name: 'Barclay Els',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/barclay_els.png',
    },
    {
      name: 'Ciaran aep Easnillien',
      strength: 3,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/ciaran_aep_easnillien.png',
    },
    {
      name: 'Dennis Cranmer',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/cards/scoiatael/dennis_cranmer.png',
    },
    {
      name: 'Dol Blathanna Archer',
      strength: 4,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/dol_blathanna_archer.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/dol_blathanna_scout.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/dol_blathanna_scout.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/dol_blathanna_scout.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/dwarven_skirmisher.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/dwarven_skirmisher.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/dwarven_skirmisher.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/elven_skirmisher.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/elven_skirmisher.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/elven_skirmisher.png',
    },
    {
      name: 'Filavandrel aen Fidhail',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/filavandrel.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/cards/scoiatael/havekar_healer.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/cards/scoiatael/havekar_healer.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/cards/scoiatael/havekar_healer.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/havekar_smuggler.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/havekar_smuggler.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/cards/scoiatael/havekar_smuggler.png',
    },
    {
      name: 'Milva',
      strength: 10,
      description: 'Gain +1 power for each card in the same row.',
      isHero: false,
      range: 'RANGED',
      ability: 'MORAL_BOOST',
      imageUrl: '/cards/scoiatael/milva.png',
    },
    {
      name: 'Riordain',
      strength: 1,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/riordain.png',
    },
    {
      name: 'Toruviel',
      strength: 2,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/toruviel.png',
    },
    {
      name: 'Vrihedd Brigade Recruit',
      strength: 4,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/cards/scoiatael/vrihedd_recruit.png',
    },
    {
      name: 'Vrihedd Brigade Veteran',
      strength: 5,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/vrihedd_veteran.png',
    },
    {
      name: 'Yaevinn',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: ['MELEE', 'RANGED'],
      ability: 'AGILE',
      imageUrl: '/cards/scoiatael/yaevinn.png',
    },
    {
      name: 'Saesenthessis',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/saesenthessis.png',
    },
    {
      name: 'Eithné',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/eithne.png',
    },
    {
      name: 'Isengrim Faoiltiarna',
      strength: 10,
      description: 'Hero with morale boost.',
      isHero: true,
      range: 'MELEE',
      ability: 'MORAL_BOOST',
      imageUrl: '/cards/scoiatael/isengrim.png',
    },
    {
      name: 'Ida Emean aep Sivney',
      strength: 6,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/ida_emean.png',
    },
    {
      name: 'Iorveth',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/cards/scoiatael/iorveth.png',
    },
    {
      name: 'Schirrú',
      strength: 8,
      description: 'Destroy enemy siege units if total siege >= 10.',
      isHero: false,
      range: 'SIEGE',
      ability: 'SCORCH',
      imageUrl: '/cards/scoiatael/schirru.png',
    },
  ],
  leaders: [
    {
      name: 'Francesca Findabair – Daisy of the Valley',
      description: 'Draw an extra card at the beginning of the battle.',
      imageUrl: '/leaders/scoiatael/francesca_daisy_of_the_valley.png',
      ability: 'DRAW_EXTRA_CARD',
    },
    {
      name: 'Francesca Findabair – Hope of the Aen Seidhe',
      description: 'Move agile units to whichever row maximizes their strength.',
      imageUrl: '/leaders/scoiatael/francesca_hope_of_the_aen_seidhe.png',
      ability: 'OPTIMIZE_AGILE_UNITS',
    },
    {
      name: 'Francesca Findabair – Pureblood Elf',
      description: 'Pick a Biting Frost card from your deck and play it instantly.',
      imageUrl: '/leaders/scoiatael/francesca_pureblood_elf.png',
      ability: 'PLAY_FROST_FROM_DECK',
    },
    {
      name: 'Francesca Findabair – Queen of Dol Blathanna',
      description:
        "Destroy your enemy's strongest Close Combat unit(s) if the combined strength of all his Close Combat units is 10 or more.",
      imageUrl: '/leaders/scoiatael/francesca_queen_of_dol_blathanna.png',
      ability: 'SCORCH_MELEE',
    },
    {
      name: 'Francesca Findabair – The Beautiful',
      description: 'Doubles the strength of all your Ranged Combat units.',
      imageUrl: '/leaders/scoiatael/francesca_the_beautiful.png',
      ability: 'HORN_RANGED',
    },
  ],
};
