import type { FactionConfig } from '../../../types/game/FactionConfig';

export const SCOIATAEL: FactionConfig = {
  name: 'Scoia’tael',
  iconUrl: '',
  cardBackIconUrl: '/back/scoiatael_back.jpg',
  units: [
    {
      name: 'Barclay Els',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/barclay_els.png',
    },
    {
      name: 'Ciaran aep Easnillien',
      strength: 3,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/ciaran_aep_easnillien.png',
    },
    {
      name: 'Dennis Cranmer',
      strength: 6,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/scoiatael/dennis_cranmer.png',
    },
    {
      name: 'Dol Blathanna Archer',
      strength: 4,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/scoiatael/dol_blathanna_archer.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/dol_blathanna_scout_1.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/dol_blathanna_scout_2.png',
    },
    {
      name: 'Dol Blathanna Scout',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/dol_blathanna_scout_3.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/dwarven_skirmisher_1.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/dwarven_skirmisher_2.png',
    },
    {
      name: 'Dwarven Skirmisher',
      strength: 3,
      description: 'Summons all Dwarven Skirmisher cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/dwarven_skirmisher_3.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/elven_skirmisher_1.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/elven_skirmisher_2.png',
    },
    {
      name: 'Elven Skirmisher',
      strength: 2,
      description: 'Summons all Elven Skirmisher cards from your deck.',
      isHero: false,
      range: 'RANGED',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/elven_skirmisher_3.png',
    },
    {
      name: 'Filavandrel aen Fidhail',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/filavandrel_aen_fidhail.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/scoiatael/havekar_healer_2.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/scoiatael/havekar_healer_2.png',
    },
    {
      name: 'Havekar Healer',
      strength: 0,
      description: 'Resurrect a card from the discard pile.',
      isHero: false,
      range: 'RANGED',
      ability: 'MEDIC',
      imageUrl: '/scoiatael/havekar_healer_3.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/havekar_smuggler_1.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/havekar_smuggler_2.png',
    },
    {
      name: 'Havekar Smuggler',
      strength: 5,
      description: 'Summons all Havekar Smuggler cards from your deck.',
      isHero: false,
      range: 'MELEE',
      ability: 'MUSTER',
      imageUrl: '/scoiatael/havekar_smuggler_3.png',
    },
    {
      name: 'Milva',
      strength: 10,
      description: 'Gain +1 power for each card in the same row.',
      isHero: false,
      range: 'RANGED',
      ability: 'MORAL_BOOST',
      imageUrl: '/scoiatael/milva.png',
    },
    {
      name: 'Riordain',
      strength: 1,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/scoiatael/riordain.png',
    },
    {
      name: 'Toruviel',
      strength: 2,
      description: 'No special ability.',
      isHero: false,
      range: 'RANGED',
      imageUrl: '/scoiatael/toruviel.png',
    },
    {
      name: 'Vrihedd Brigade Recruit',
      strength: 4,
      description: 'No special ability.',
      isHero: false,
      range: 'MELEE',
      imageUrl: '/scoiatael/vrihedd_brigade_recruit.png',
    },
    {
      name: 'Vrihedd Brigade Veteran',
      strength: 5,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/vrihedd_brigade_veteran_1.png',
    },
    {
      name: 'Vrihedd Brigade Veteran',
      strength: 5,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/vrihedd_brigade_veteran_2.png',
    },
    {
      name: 'Yaevinn',
      strength: 6,
      description: 'Can be placed on melee or ranged row.',
      isHero: false,
      range: 'AGILE',
      ability: 'AGILE',
      imageUrl: '/scoiatael/yaevinn.png',
    },
    {
      name: 'Saesenthessis',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/scoiatael/saesenthessis.png',
    },
    {
      name: 'Eithné',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/scoiatael/eithne.png',
    },
    {
      name: 'Isengrim Faoiltiarna',
      strength: 10,
      description: 'Hero with morale boost.',
      isHero: true,
      range: 'MELEE',
      ability: 'MORAL_BOOST',
      imageUrl: '/scoiatael/isengrim_faolitarna.png',
    },
    {
      name: 'Ida Emean aep Sivney',
      strength: 6,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/scoiatael/ida_emean_aep_sivney.png',
    },
    {
      name: 'Iorveth',
      strength: 10,
      description: 'Hero. Immune to special cards and abilities.',
      isHero: true,
      range: 'RANGED',
      imageUrl: '/scoiatael/iorveth.png',
    },
    {
      name: 'Schirrú',
      strength: 8,
      description: 'Destroy enemy siege units if total siege >= 10.',
      isHero: false,
      range: 'SIEGE',
      ability: 'SCORCH',
      imageUrl: '/scoiatael/schirru.png',
    },
  ],
  leaders: [
    {
      name: 'Francesca Findabair – Daisy of the Valley',
      description: 'Draw an extra card at the beginning of the battle.',
      imageUrl: '/scoiatael/francesca_findabair_daisy_of_the_valle.png',
      ability: 'DRAW_EXTRA_CARD',
    },
    {
      name: 'Francesca Findabair – Hope of the Aen Seidhe',
      description: 'Move agile units to whichever row maximizes their strength.',
      imageUrl: '/scoiatael/francesca_findabair_hope_of_the_aen_seidhe.png',
      ability: 'OPTIMIZE_AGILE_UNITS',
    },
    {
      name: 'Francesca Findabair – Pureblood Elf',
      description: 'Pick a Biting Frost card from your deck and play it instantly.',
      imageUrl: '/scoiatael/francesca_findabair_pureblood_elf.png',
      ability: 'PLAY_FROST_FROM_DECK',
    },
    {
      name: 'Francesca Findabair – Queen of Dol Blathanna',
      description:
        "Destroy your enemy's strongest Close Combat unit(s) if the combined strength of all his Close Combat units is 10 or more.",
      imageUrl: '/scoiatael/francesca_findabair_queen_of_dol_blathanna.png',
      ability: 'SCORCH_MELEE',
    },
    {
      name: 'Francesca Findabair – The Beautiful',
      description: 'Doubles the strength of all your Ranged Combat units.',
      imageUrl: '/scoiatael/francesca_findabair_the_beautiful.png',
      ability: 'HORN_RANGED',
    },
  ],
};
